### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by grosser** [grosser/fast_gettext#115]
rewrote a lot of code to make things faster and more consistent ... also simpler hopefully

@rgraff would appreciate a sanity check before I release this ...

**Comment by rgraff** [comment]
A lot of changes. The only issue I have is with unifying the namespace separator:

https://github.com/grosser/fast_gettext/commit/a3a2ad5a9b38e1af760ddf2014a684dafa0e2d0a

While you do reduce the cache size for people who use `s_("Fruit|Apple")` and `p_("Fruit","Apple")` unintentionally; ruby-gettext, the file format, and common translation tools allow for different values that the cache no longer respects.

For example, this is valid:

```
msgctxt "Tree Fruit"
msgid "Apple"
msgstr "Apfel"

msgid "Tree Fruit|Apple"
msgstr "Frucht des Apfelbaum"
```

And supported in the commonly used poedit:

<img width="440" alt="example po goldstar 1 0 0 2018-12-20 09-04-50" src="https://user-images.githubusercontent.com/8323/50299407-5908ba00-0436-11e9-83b5-8db47c115018.png">

But I'm unsure which will be returned in a unified namespace cache.

I would prefer to maintain compatibility and being consistent with the rest of the tools in the gettext ecosystem.

I do think this warrants a note or warning in the readme, however, telling people that having `s_("Fruit|Apple")` and `p_("Fruit","Apple")` will require an additional translation and take up more memory.

**Comment by grosser** [comment]
hmm yeah good point ... I'll that back and add a note :(

**Comment by grosser** [comment]
ok, added that back ... do you see any other issues ?

**Comment by rgraff** [comment]
No other issues
