### ISSUE TITLE
All tests fail in application without ActiveRecord

### ISSUE THREAD

**Issue by marcinmantke** [grosser/fast_gettext#120]
I have a Rails 6 application which doesn't use relational DB and doesn't have ActiveRecord included. Unfortunately, there is a `require "active_record"` statement in https://github.com/grosser/fast_gettext/blob/master/lib/fast_gettext/translation_repository/db.rb#L3 which makes all my specs fail due to empty relational DB config. Is ActiveRecord required in project for this library to work?

**Comment by grosser** [comment]
No it's not, the `db` should not be loaded automatically ... can you make a
PR to fix that (change to autoload) ?

**Comment by marcinmantke** [comment]
@grosser I think that `Db` class should be loaded automatically but this class doesn't depend on active record in any way. Of course apart from `require_models` method, which in my opinion can have `require "active_record"` statement. I'll try to make a PR with that change.

**Comment by grosser** [comment]
2.0.2
