### ISSUE TITLE
is Rails 6 supported?

### ISSUE THREAD

**Issue by mathieujobin** [grosser/fast_gettext#129]
I can't get FastGettext to pick up my po/mo files anymore. I'm not sure what has changed.

is still gem still supported ?

**Comment by grosser** [comment]
idk why it would break, please try messing with the gettext_i18n_rails exapmple to fix it for rrails 6

**Comment by mathieujobin** [comment]
I found out I needed to setup the `available_locales` on the `I18n` module as well, not only `FastGettext`, and its working now

thanks
