### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by bl-ue** [grosser/fast_gettext#131]
Hello, I just noticed that the description of this repo has a typo:

>Ruby GetText, but 12x faster + 530x less garbage + simple + clean namespace + **threadsave** + extendable + multiple backends

Should be:

>Ruby GetText, but 12x faster + 530x less garbage + simple + clean namespace + **threadsafe** + extendable + multiple backends

*threadsa**v**e* vs. *threadsa**f**e* :)

**Comment by grosser** [comment]
thx, fixed!
