### ISSUE TITLE
Support for cache storages - Proposal

### ISSUE THREAD

**Issue by basex** [grosser/fast_gettext#67]
What do you think about adding the option to add a different cache storage besides a Hash in Memory?

Could easily be done with Moneta or ActiveSupport::Cache.

I made a simple implementation and tested with Memcache and Redis backends and seems to work ok: https://github.com/basex/fast_gettext/commits/master

**Comment by basex** [comment]
> Might be best to preload all the translations in the master before forking
> (no memory used in children), we are doing this or our top 10 used
> translations.

@grosser is it possible you provide an example on how you are doing this?

**Comment by grosser** [comment]
Easiest is to use each translation for example from a before-fork block

**Comment by basex** [comment]
@grosser thanks for the quick reply. I thought there was some method to load all to the cache.

I will give it a try.
