### ISSUE TITLE
Include files outside lib/ in the gem

### ISSUE THREAD

**Issue by domcleal** [grosser/fast_gettext#70]
590ce71fc23441bdad72d6d713474d3ace3e04ec changed the gemspec to only include files under lib/ in the resulting gem, but it'd be useful to keep others in there.

The gem is repackaged in Fedora and elsewhere, so the spec/ dir is useful to be able to run the tests at build time to check it still works.  The README and CHANGELOG are also useful for users (and important, since it specifies the licence).

**Comment by grosser** [comment]
- shipping readme + changelog in 0.9.1
 - not going to ship specs since they are useless and nobody runs them + nobody is able to run them without the proper gemfile and gemfile.lock and setup

**Comment by domcleal** [comment]
Ok, thanks for the release @grosser.

I'm not sure about the specs for the record - as an example, [the Fedora package runs them](http://pkgs.fedoraproject.org/cgit/rubygem-fast_gettext.git/tree/rubygem-fast_gettext.spec#n50) to confirm the package is functional against the gems available in the package repos (bundler, Gemfiles etc aren't used).  @voxik is the maintainer, so it'll be up to him, but I guess the specs might have to come from git instead?

**Comment by grosser** [comment]
yep, fetch from git or so ... chances are most projects specs won't run
either way since they need a test-db and whatever setup is in .travis.yml
