### ISSUE TITLE
Question: how fallback translation from pt_BR to pt?

### ISSUE THREAD

**Issue by brauliobo** [grosser/fast_gettext#74]
(Sorry to use the issue tracker to ask something. I really couldn't figure out how to do this)

I need to support country specific languages, for example, `pt_BR`, `en_US`, etc. But if the translation is not found, then it should lookup on a general language translation (e.g. `pt`, `en`).

How can I achieve that? I've tried to do with chains but couldn't...

Thanks!

**Comment by grosser** [comment]
I don't know if this is supported, how about adding all missing words from pt_BR to pt -> no need to fallback at all ?

**Comment by brauliobo** [comment]
@grosser how to do that in a programatic way?

**Comment by brauliobo** [comment]
@grosser what do you think if I implement something similar to https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/fallbacks.rb on fastgettext?

**Comment by grosser** [comment]
I think the simpler / faster way is generating the fallbacks into the
translations.
If you use yml/json that should be straight forward, for po/mo you can use
https://github.com/grosser/get_pomo to read/write them.
Basically read pt_BR and check which keys are in pt/en but not in there ->
fill them out.

On Sat, Feb 7, 2015 at 7:54 AM, Bráulio Bhavamitra <notifications@github.com

**Comment by brauliobo** [comment]
Well, i decided to dive a bit deeper to do it automatically. Here is what I've got:

```ruby
class FastGettext::TranslationRepository::Base
  attr_accessor :files
end
class FastGettext::MoFile
  attr_accessor :data
end
module FastGettext
  @@fallbacks = { 
    'en_US' => 'en',
    'pt_BR' => 'pt',
    'fr_FR' => 'fr',
    'hy_AM' => 'hy',
    'de_DE' => 'de',
    'ru_RU' => 'ru',
    'es_ES' => 'es',
    'it_IT' => 'it',
  }

  def self.fallbacks
    @@fallbacks
  end 
end

FastGettext.translation_repositories.each do |domain, repository|
  repository.chain.each do |chain|
    new_files = {}

    files = chain.files
    files.each do |locale, file|
      FastGettext.fallbacks.each do |dest, source|
        next if locale != source

        mo_file = files[dest]
        unless mo_file
          mo_file ||= FastGettext::MoFile.empty
          new_files[dest] = mo_file
        end

        mo_file.data = file.data.merge mo_file.data
      end
    end

    files.merge! new_files
  end
end
```

What do you think?

**Comment by grosser** [comment]
Looks good :)

**Comment by danschultzer** [comment]
:+1: @brauliobo

**Comment by brauliobo** [comment]
updated with newer code used: only merge when fallback data exists, otherwise just use the data hash from the source. This frees some memory :)

**Comment by grosser** [comment]
hmm this is doing it at runtime, would it be more efficient to do it before generating mo files ?

**Comment by brauliobo** [comment]
@grosser yeah, on runtime, as all of our fallbacks are just aliases and have no custom locales. So the cost is just a simple assignment. As they are aliases it wouldn't make sense to add them to git.
