### ISSUE TITLE
Slow load of lot of locales. How to lazy load?

### ISSUE THREAD

**Issue by brauliobo** [grosser/fast_gettext#75]
I noticed that with lots of locales (mo) files fastgettext significantly increases rails boot time.

I've tried to delay load using `Thread.new`, but can't because translation is called before and then I'll get the error `Current textdomain ("noosfero") was not added, use FastGettext.add_text_domain ! (FastGettext::Storage::NoTextDomainConfigured)`.

Maybe a lazy load would help, is that possible? Also, a lot of memory goes to locales...

**Comment by grosser** [comment]
lazy load would be great for development and test (production should preload everything to get benefits from copy-on-write when using forked servers), all we really need at boot is to know the local names for available_locales. maybe you can come up with a LazyMo backend that inherits from Mo and uses something like `@loaded` to keep track of if stuff is already loaded / still needs to be loaded.

**Comment by tstrachota** [comment]
@grosser I guess we can close this issue now.
