### ISSUE TITLE
support proper namespacing "p_"

### ISSUE THREAD

**Issue by dfherr** [grosser/fast_gettext#87]
I would very much appreciate the support for proper namespaces using the `p_` context method.

I know that `s_` kind of does the same, but with one big exception: It writes the context into the msgid and doesn't use the msgctxt entry of the po file. This especially makes a difference for translators, which are not allowed to edit msgctxt, but can edit the whole msgid.

p_("Namespace","message")
```
msgctxt "Namespace"
msgid "message"
```

s_("Namespace|message")
```
msgid "Namespace|message"
```

**Comment by grosser** [comment]
idk about msgctxt ... if you can make a PR that does not break everything
else / makes everything else slower then that sounds fine :)

**Comment by mhulet** [comment]
+1. The way `p()` generates the .pot file isn't working with POEditor.com.

**Comment by grosser** [comment]
go make a PR then :D

**Comment by connorshea** [comment]
Just wanted to add that [we're also interested in this at GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/40347) :) We'll try to make time to contribute it.

**Comment by grosser** [comment]
🍿 can't wait :)

**Comment by rgraff** [comment]
I have PR #105 to implement the `p_` translation method as an alternative syntax so `s_`. I believe this issue is in regards to reading the .po file and using the msgxtxt when present.
