### ISSUE TITLE
Backport file read encoding fix to Ruby 1.9 compatible version

### ISSUE THREAD

**Issue by Magisus** [grosser/fast_gettext#99]
We are using this library to load translations from PO files in a project that requires Ruby 1.9 compatibility due to the need to use JRuby 1.7. We are therefore stuck on the 1.1.0 version of this gem, because 1.2.0 requires Ruby >= 2. On some users' systems, we have run into the bug where parsing PO files fails due to Ruby reading the files with the incorrect encoding. The bug was fixed in this patch https://github.com/grosser/fast_gettext/commit/8b65ff3da69f031e5647f3d58b4d5b9cbd6b229d, but as I stated above, we are unable to move to that version of the gem due to the Ruby version constraint.

Would you be willing to branch from the 1.1.0 tag and release a 1.1.1 version of the gem with that patch applied (like on this branch https://github.com/magisus/fast_gettext/tree/po-encode-backport, which I have verified fixes the bug for us)? I would be happy to create the branch and push it to the repo; we would only need you to do the actual gem release.

We are actively working to move to JRuby 9K, which would remove the need for this, but at present some serious performance regressions are preventing the upgrade. Until that gets resolved and we are able to update which version of this gem we use, parsing PO files fails hard if the system locale settings are not perfectly configured (this causes problems particularly for Windows) in ways we can't always influence on users' machines.

**Comment by grosser** [comment]
sounds good, can you use `grosser/v1.1-stable` via github and tell me if
that works ?
gem 'fast_gettext', git: 'https://github.com/grosser/fast_gettext', branch:
'grosser/v1.1-stable'

**Comment by grosser** [comment]
travis seems to not like it ... maybe you can get it to work properly:

https://travis-ci.org/grosser/fast_gettext/jobs/325645688

**Comment by Magisus** [comment]
I'll take a look. Thanks for doing this!

**Comment by Magisus** [comment]
So, I can fix the Travis failures by putting back in the Ruby 1.8 compatibility check and updating a couple of specs, but given that Ruby 1.8 (and by extension Ruby Enterprise Edition) went end-of-life in 2012, might it make more sense to just remove those from the Travis testing matrix? I'll leave the decision up to you, I've opened https://github.com/grosser/fast_gettext/pull/100 with the compatibility fixes.

**Comment by grosser** [comment]
1.1.1 is out 🎉

**Comment by Magisus** [comment]
Thank you so much!
